[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
felys = { git = "https://github.com/felys-lang/felys" }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
tower-http = { version = "0.5", features = ["cors"] }
axum = "0.7"
